name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby (for xcpretty, optional)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build and test
        run: |
          SCHEME="FlickrTest"
          DESTINATION="platform=iOS Simulator,name=iPhone 16,OS=18.5"
          set -o pipefail
          xcodebuild test -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES
